version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - appbar
  - ahooks
  - astro
  - astrojs
  - attributify
  - autosize
  - avvvatars
  - chatgpt
  - cognitiveservices
  - contexify
  - csstype
  - davinci
  - eventsource
  - heroicons
  - highlightjs
  - Inputbar
  - jridgewell
  - justjavac
  - katex
  - linkify
  - lokijs
  - msgtype
  - nozbe
  - npmmirror
  - openai
  - plusplus
  - preact
  - prefs
  - preinstall
  - reduxjs
  - tailwindcss
  - timeago
  - tippyjs
  - tsconfigs
  - undici
  - unocss
  - upsert
  - Vditor
  - watermelondb
ignoreWords:
  - trivago
  - zhengxs
